#config_version=6

light_settings:
    default_fade_ms: 40
lights:
  # Backbox Lamps
  l_player_1_score_indicator:
    number: backbox-1-1
    type: grb
    label: player active 1
    default_on_color: F3C35F
  l_high_score_indicator:
    number: backbox-1-2
    type: grb
    label: high score
    default_on_color: F3C35F
  l_player_2_score_indicator:
    number: backbox-1-3
    type: grb
    label: player active 2
    default_on_color: F3C35F
  l_player_3_score_indicator:
    number: backbox-1-4
    type: grb
    label: player active 3
    default_on_color: F3C35F
  l_player_4_score_indicator:
    number: backbox-1-5
    type: grb
    label: player active 4
    default_on_color: F3C35F
  l_tilt:
    number: backbox-1-6
    type: grb
    default_on_color: F3C35F
  l_player_4_indicator:
    number: backbox-1-7
    type: grb
    default_on_color: F3C35F
  l_player_3_indicator:
    number: backbox-1-8
    type: grb
    default_on_color: F3C35F
  l_player_2_indicator:
    number: backbox-1-9
    type: grb
    default_on_color: F3C35F
  l_player_1_indicator:
    number: backbox-1-10
    type: grb
    default_on_color: F3C35F
  l_fire_again_1:
    number: backbox-1-11
    type: grb
    tags: t_fire_again
    default_on_color: F3C35F
  l_fire_again_2:
    number: backbox-1-12
    type: grb
    tags: t_fire_again
    default_on_color: F3C35F
  l_ball_in_play:
    number: backbox-1-14
    type: grb
    default_on_color: F3C35F
  l_match:
    number: backbox-1-13
    type: grb
    default_on_color: F3C35F
  l_game_over_1:
    number: backbox-1-15
    type: grb
    tags: t_game_over
    default_on_color: F3C35F
  l_game_over_2:
    number: backbox-1-16
    type: grb
    tags: t_game_over
    default_on_color: F3C35F

#######################################
# Jet Bumper Lights, 8 LED's per unit #
#######################################
  # l_jetbumper_1_1:
  #   channels:
  #     red:
  #       - number: backbox-2-1
  #     green:
  #       - number: backbox-2-2
  #     blue:
  #       - number: backbox-2-3
  #     white:
  #       - number: backbox-2-4
  #   tags: l_jetbumper_1
    #default_on_color: 00F3C35F
  
  # l_jetbumper_1_2:
  #   number: backbox-2-2
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_3:
  #   number: backbox-2-3
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_4:
  #   number: backbox-2-4
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_5:
  #   number: backbox-2-5
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_6:
  #   number: backbox-2-6
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_7:
  #   number: backbox-2-7
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_1_8:
  #   number: backbox-2-8
  #   type: grb
  #   tags: l_jetbumper_1
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_1:
  #   number: backbox-2-9
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_2:
  #   number: backbox-2-10
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_3:
  #   number: backbox-2-11
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_4:
  #   number: backbox-2-12
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_5:
  #   number: backbox-2-13
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_6:
  #   number: backbox-2-14
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_7:
  #   number: backbox-2-15
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F
  
  # l_jetbumper_2_8:
  #   number: backbox-2-16
  #   type: grb
  #   tags: l_jetbumper_2
  #   default_on_color: F3C35F

  # l_jetbumper_3_1:
  #   number: backbox-2-17
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_2:
  #   number: backbox-2-18
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_3:
  #   number: backbox-2-19
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_4:
  #   number: backbox-2-20
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_5:
  #   number: backbox-2-21
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_6:
  #   number: backbox-2-22
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_7:
  #   number: backbox-2-23
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_3_8:
  #   number: backbox-2-24
  #   type: grb
  #   tags: l_jetbumper_3
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_1:
  #   number: backbox-2-25
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_2:
  #   number: backbox-2-26
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_3:
  #   number: backbox-2-27
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_4:
  #   number: backbox-2-28
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_5:
  #   number: backbox-2-29
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_6:
  #   number: backbox-2-30
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_7:
  #   number: backbox-2-31
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  # l_jetbumper_4_8:
  #   number: backbox-2-32
  #   type: grb
  #   tags: l_jetbumper_4
  #   default_on_color: F3C35F
  
  #######################################
  # Playfield lamps                     #
  #######################################
  l_fire_lane_1000_when_lit:
    number: playfield-1-1
    type: rgb
  
  ## Lock 1
  l_lock_1_star_rollover:
    number: playfield-1-2
    type: rgb
  l_lock_1_arrow:
    number: playfield-1-3
    type: rgb

  ## Lock 2  
  l_lock_2_star_rollover:
    number: playfield-3-1
    type: rgb
  l_lock_2_arrow:
    number: playfield-3-2
    type: rgb


  l_shield:
    number: playfield-1-4
    type: rgb
    default_on_color: F3C35F
  l_left_return_lane_3000_when_lit:
    number: playfield-1-5
    type: rgb
    default_on_color: F3C35F
  l_left_outlane_special:
    number: playfield-1-6
    type: rgb
    default_on_color: F3C35F
  l_left_outlane_illumination_left:
    number: playfield-1-7
    type: grb
    default_on_color: F3C35F
  l_left_outlane_illumination_right:
    number: playfield-1-8
    type: grb
    default_on_color: F3C35F
  l_bonus_multiplier_2x:
    number: playfield-1-9
    type: rgb
    tags: l_bonus_multipliers
    default_on_color: warm_white
  l_bonus_multiplier_3x:
    number: playfield-1-10
    type: rgb
    tags: l_bonus_multipliers
    default_on_color: warm_white
  l_fire_lamp_3:
    number: playfield-1-11
    type: grb
    tags: l_fire
  l_fire_lamp_2:
    number: playfield-1-12
    type: grb
    tags: l_fire
  l_fire_lamp_1:
    number: playfield-1-13
    type: grb
    tags: l_fire
  
  ## Arrows
  l_arrow_1:
    number: playfield-2-1
    type: rgb
    default_on_color: F3C35F
  l_arrow_2:
    number: playfield-2-2
    type: rgb
    default_on_color: F3C35F
  l_arrow_3:
    number: playfield-2-3
    type: rgb
    default_on_color: F3C35F
  l_arrow_4:
    number: playfield-2-4
    type: rgb
    default_on_color: F3C35F
  l_arrow_5:
    number: playfield-2-5
    type: rgb
    default_on_color: F3C35F
  l_arrow_6:
    number: playfield-2-6
    type: rgb
    default_on_color: F3C35F

  ## Bonus indicator lamps
  l_bonus_1:
    number: playfield-2-17
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_1, led_bns_adv
  l_bonus_2:
    number: playfield-2-16
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_2, led_bns_adv
  l_bonus_3:
    number: playfield-2-15
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_3, led_bns_adv
  l_bonus_4:
    number: playfield-2-14
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_4, led_bns_adv
  l_bonus_5:
    number: playfield-2-13
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_5, led_bns_adv
  l_bonus_6:
    number: playfield-2-12
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_6, led_bns_adv
  l_bonus_7:
    number: playfield-2-11
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_7, led_bns_adv
  l_bonus_8:
    number: playfield-2-10
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_8, led_bns_adv
  l_bonus_9:
    number: playfield-2-9
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_9, led_bns_adv
  l_bonus_10:
    number: playfield-2-8
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_10, led_bns_adv
  l_bonus_20:
    number: playfield-2-7
    type: rgb
    default_on_color: F3C35F
    tags: led_bns_adv_20, led_bns_adv
  

  l_fire_again:
    number: playfield-2-18
    type: rgb
    default_on_color: F3C35F

  l_right_target_1:
    number: playfield-3-3
    type: rgb
    default_on_color: blue
  l_right_target_2:
    number: playfield-3-4
    type: rgb
    default_on_color: blue
  l_right_target_3:
    number: playfield-3-5
    type: rgb
    default_on_color: blue
  l_extra_ball_arrow:
    number: playfield-3-6
    type: rgb
    default_on_color: F3C35F
  l_right_outlane_special:
    number: playfield-3-7
    type: rgb
    default_on_color: F3C35F
  l_right_return_lane_3000_when_lit:
    number: playfield-3-8
    type: rgb
    default_on_color: F3C35F
  l_power_lamp_3:
    number: playfield-3-9
    type: grb
    tags: l_power
    default_on_color: F3C35F
  l_power_lamp_2:
    number: playfield-3-10
    type: grb
    tags: l_power
    default_on_color: F3C35F
  l_power_lamp_1:
    number: playfield-3-11
    type: grb
    tags: l_power
    default_on_color: F3C35F
  l_right_outlane_illumination_left:
    number: playfield-3-12
    type: grb
    default_on_color: F3C35F
  l_right_outlane_illumination_right:
    number: playfield-3-13
    type: grb
    default_on_color: F3C35F
  l_bonus_multiplier_5x:
    number: playfield-3-14
    type: rgb
    tags: l_bonus_multipliers
    default_on_color: warm_white
  l_bonus_multiplier_4x:
    number: playfield-3-15
    type: rgb
    tags: l_bonus_multipliers
    default_on_color: warm_white
  l_lane_f:
    number: playfield-4-1
    type: rgb
    default_on_color: warm_white
  l_lock_3_arrow:
    number: playfield-4-2
    type: rgb
    default_on_color: F3C35F
  l_lane_i:
    number: playfield-4-3
    type: rgb
    default_on_color: warm_white
  l_lane_r:
    number: playfield-4-4
    type: rgb
    default_on_color: warm_white
  l_lane_e:
    number: playfield-4-5
    type: rgb
    default_on_color: warm_white
  l_fire_lane_guide_4:
    number: playfield-4-10
    type: grb
    tags: fire_lane_guides
  l_fire_lane_guide_3:
    number: playfield-4-9
    type: grb
    tags: fire_lane_guides
  l_target_score_1000:
    number: playfield-4-8
    type: grb
    tags: fire_lane_guides
  l_fire_lane_guide_2:
    number: playfield-4-7
    type: grb
    tags: fire_lane_guides
  l_fire_lane_guide_1:
    number: playfield-4-6
    type: grb
    tags: fire_lane_guides
  l_target_score_10000:
    number: playfield-4-11
    type: rgb
    default_on_color: F3C35F
  l_target_score_30000:
    number: playfield-4-12
    type: rgb
    default_on_color: F3C35F
  l_target_score_50000:
    number: playfield-4-13
    type: rgb
    default_on_color: F3C35F

  