#config_version=6
mode:
  start_events: start_mode_jet_bumpers
  stop_events: ball_ended
  priority: 100

show_player:
  mode_shield_started: jet_bumpers_on_show
  mode_shield_stopped: jet_bumpers_off_show